In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.random.randn(5,5).astype(np.float32)

array([[ 0.48667386, -1.7433242 ,  0.33523032,  0.12361102, -1.9108891 ],
       [-0.71581197,  1.0809956 , -0.9705165 , -1.29869   , -0.14069273],
       [ 0.01485328,  1.2721941 ,  0.36144558,  0.0315692 ,  0.9343016 ],
       [-1.3051839 ,  0.3980876 , -0.41050267,  0.64625967,  0.5512808 ],
       [ 0.5509824 ,  1.1741592 , -0.0899285 , -0.19402379, -2.6475413 ]],
      dtype=float32)

In [4]:
s = np.empty((5,1), dtype = np.float32)

In [5]:
s

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [6]:
s.shape

(5, 1)

In [7]:
np.random.randn(*s.shape)

array([[-1.8837891 ],
       [-0.92148103],
       [-1.24102269],
       [-1.04055577],
       [-1.09469844]])

In [8]:
np.random.randint(0,100,5)

array([15, 53, 22, 11, 80])

In [9]:
from itertools import islice

In [10]:
list(islice('asdafdsafdas',5))

['a', 's', 'd', 'a', 'f']

In [12]:
whole = []
with open("F:/MSc DS/Project/dms/trained_dms_txt/word2dm.txt") as f:
    for line in f:
        linelist = line.split()
        for a in linelist:
            whole.append(a)
f.close

<function TextIOWrapper.close()>

In [14]:
n =len(whole)/290

In [15]:
n

288467.0

In [16]:
dicA = []
dicB = []
val = []

In [17]:
with open("F:/MSc DS/Project/compositional datasets/KS2016-SV.txt") as f:
    for line in f:
        linelist = line.split(",")
        dicA.append(linelist[0])
        dicB.append(linelist[1])
        val.append(linelist[2])

In [18]:
dicB

['information express',
 'evidence suggest',
 'group think',
 'people believe',
 'material show',
 'paper present',
 'facility meet',
 'station serve',
 'work show',
 'survey reveal',
 'person create',
 'student develop',
 'organization manage',
 'company operate',
 'contestant compete',
 'player play',
 'examination show',
 'study demonstrate',
 'message travel',
 'news come',
 'season end',
 'Summer finish',
 'document state',
 'report note',
 'product supply',
 'book offer',
 'plant grow',
 'tree mature',
 'text state',
 'title suggest',
 'person decide',
 'player choose',
 'group intend',
 'government plan',
 'information inform',
 'News report',
 'condition continue',
 'problem persist',
 'scientist accept',
 'researcher believe',
 'force attack',
 'army invade',
 'object travel',
 'aircraft fly',
 'change affect',
 'movement influence',
 'person come',
 'man approach',
 'publication produce',
 'magazine publish',
 'child leave',
 'son escape',
 'building open',
 'theatre reopen',

In [19]:
val

['T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',
 'F\n',
 'T\n',


In [23]:

import numpy as np

whole = []
with open("F:/MSc DS/Project/dms/trained_dms_txt/ms-word2dm-d10.txt") as f:
    for line in f:
        linelist = line.split()
        for a in linelist:
            whole.append(a)
f.close
n =len(whole)/290
voc = []
for i in range(int(n)):
    voc.append(whole[i*290])
dic ={}
for i in range(int(n)):
    a = whole[i*290+1:(i+1)*290]
    a =np.array(a,dtype = 'float')
    a.resize([17,17])
    dic[voc[i]]=a


In [51]:
type(dic.keys())

dict_keys

In [52]:
dic.keys()

dict_keys(['the', 'baronet', 'supreme', 'be', 'upholster', 'use', 'a', 'needle', 'tease', 'hair', 'pad', 'to', 'provide', 'extra', 'support', 'make', 'it', 'as', 'comfortable', 'affordable', 'each', 'individual', 'pocket', 'spring', 'enclose', 'in', 'fine', 'quality', 'cotton', 'calico', 'for', 'its', 'durability', 'and', 'breathing', 'property', 'picture', 'here', 'an', 'attractive', 'mulberry', 'tick', 'on', 'turn', 'wood', 'leg', 'available', 'wide', 'variety', 'of', 'mattress', 'divan', 'cover', 'one', 'many', 'model', 'feature', 'ward', 'brothers', 'bed', 'department', 'waterdale', 'doncaster', 'david', 'music', 'site', 'this', 'offer', 'no', 'obligation', 'access', 'completely', 'free', 'cd', 'album', 'downloads', 'well', 'utility', 'player', 'codecs', 'more', 'useful', 'tool', 'catch', 'submit', 'my', 'homepage', 'u', 'can', 'search', 'with', 'google', 'find', 'out', 'info', 'about', 'me', 'poem', 'from', 'famous', 'poet', 'listen', 'cool', 'weekly', 'cartoon', 'new', 'show', 'r

In [24]:
'the' in dic.keys()

True

In [25]:
len(dicA)

270

In [26]:
for i in range(len(dicA)):
    for j in dicA[i].split():
        if j.lower() not in dic.keys():
            print(i,j)

In [71]:
p1 =dicA[2].split()

In [93]:
dic[p1[0].lower()]

array([[ 2.74628210e-02, -2.64795010e-02, -1.48684100e-02,
         8.95410660e-04, -2.81778570e-02, -1.60520020e-02,
        -2.90790540e-02,  5.76216870e-03, -1.05535370e-02,
        -3.58858740e-02,  7.38213400e-03, -1.08088180e-03,
         3.35967470e-03,  2.88567270e-04, -2.60130610e-02,
         4.38402830e-03, -3.34887200e-03],
       [-2.64795010e-02,  5.67058700e-02, -4.39096940e-03,
         6.35522200e-03,  2.28050440e-02,  1.94877650e-02,
         2.95877600e-02, -5.69886200e-03,  2.17046570e-03,
         3.68092320e-02, -2.35278900e-02,  7.11457150e-03,
        -1.32940590e-02, -2.83368650e-03,  3.54943600e-02,
         1.43580970e-02,  7.96408900e-03],
       [-1.48684100e-02, -4.39096940e-03,  5.62474580e-02,
        -2.26892070e-02,  7.27907050e-02,  4.86718340e-02,
         3.62693800e-02,  8.16886750e-05,  3.26765700e-02,
         7.02793900e-02,  4.71130940e-03, -1.80621800e-02,
         1.15688825e-02,  1.43467670e-02,  4.82082930e-02,
        -3.25365960e-02, -1.6

In [94]:
dic[p1[0].lower()]

array([[ 2.74628210e-02, -2.64795010e-02, -1.48684100e-02,
         8.95410660e-04, -2.81778570e-02, -1.60520020e-02,
        -2.90790540e-02,  5.76216870e-03, -1.05535370e-02,
        -3.58858740e-02,  7.38213400e-03, -1.08088180e-03,
         3.35967470e-03,  2.88567270e-04, -2.60130610e-02,
         4.38402830e-03, -3.34887200e-03],
       [-2.64795010e-02,  5.67058700e-02, -4.39096940e-03,
         6.35522200e-03,  2.28050440e-02,  1.94877650e-02,
         2.95877600e-02, -5.69886200e-03,  2.17046570e-03,
         3.68092320e-02, -2.35278900e-02,  7.11457150e-03,
        -1.32940590e-02, -2.83368650e-03,  3.54943600e-02,
         1.43580970e-02,  7.96408900e-03],
       [-1.48684100e-02, -4.39096940e-03,  5.62474580e-02,
        -2.26892070e-02,  7.27907050e-02,  4.86718340e-02,
         3.62693800e-02,  8.16886750e-05,  3.26765700e-02,
         7.02793900e-02,  4.71130940e-03, -1.80621800e-02,
         1.15688825e-02,  1.43467670e-02,  4.82082930e-02,
        -3.25365960e-02, -1.6

In [95]:
dic[p1[1].lower()]

array([[ 5.32451530e-02,  2.14624390e-02, -8.75637400e-03,
        -4.56365400e-03, -2.82025860e-02,  2.48328500e-03,
         2.63489170e-04, -2.90562170e-04,  1.53149500e-02,
         1.32694740e-03, -1.62002180e-02,  1.96665200e-02,
        -1.05557630e-02, -1.56025000e-02, -3.70017530e-03,
         1.46703930e-02,  1.93937720e-02],
       [ 2.14624390e-02,  3.24275750e-02,  2.20399840e-03,
        -6.76601050e-03, -1.90691220e-02, -8.47580000e-03,
        -1.36759500e-02, -5.58007280e-03,  1.12829590e-02,
         3.40736590e-03, -5.99542500e-06,  6.55823670e-03,
        -2.35544130e-02, -5.52677430e-04, -8.17884600e-03,
        -3.01507420e-03, -1.07348600e-02],
       [-8.75637400e-03,  2.20399840e-03,  2.78352700e-02,
         6.65917900e-03,  1.12298870e-02,  1.02980100e-02,
        -6.34902860e-03, -2.15330780e-02, -8.57069600e-03,
         8.86072700e-03,  1.11259080e-02,  1.04638660e-02,
         2.68435220e-02,  1.25494390e-02, -6.54193340e-03,
        -1.20432440e-02, -1.1

In [109]:
dic[p1[1].lower()] * dic[p1[0].lower()]

array([[ 1.46226211e-03, -5.68314675e-04,  1.30193359e-04,
        -4.08634444e-06,  7.94688435e-04, -3.98616958e-05,
        -7.66201580e-06, -1.67426824e-06, -1.61626891e-04,
        -4.76186672e-05, -1.19592180e-04, -2.12571835e-05,
        -3.54639299e-05, -4.50237083e-06,  9.62528858e-05,
         6.43154181e-05, -6.49472600e-05],
       [-5.68314675e-04,  1.83883385e-03, -9.67768953e-06,
        -4.29994988e-05, -4.34872166e-04, -1.65174399e-04,
        -4.04640726e-04,  3.18000648e-05,  2.44892755e-05,
         1.25422522e-04,  1.41059700e-07,  4.66590439e-05,
         3.13133756e-04,  1.56611457e-06, -2.90302904e-04,
        -4.32907278e-05, -8.54933804e-05],
       [ 1.30193359e-04, -9.67768953e-06,  1.56566318e-03,
        -1.51091491e-04,  8.17431392e-04,  5.01223033e-04,
        -2.30275331e-04, -1.75900861e-06, -2.80060948e-04,
         6.22726489e-04,  5.24175949e-05, -1.89000231e-04,
         3.10549552e-04,  1.80043877e-04, -3.15375442e-04,
         3.91846165e-04,  1.9

In [97]:
new2 =dic[p2[1].lower()] + dic[p2[0].lower()]

In [98]:
type(new1)

numpy.ndarray

In [ ]:
new1 = sum()

In [79]:
def kba(a, b):
    m = b-a
    eig,_ = np.linalg.eig(m)
    Kba = sum(eig)/sum(abs(eig))
    return Kba

In [82]:
kba(new1,new2)

-1.92265846031688e-07

In [83]:
new1.shape

(17, 17)

In [87]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [90]:
type(a)

numpy.ndarray

In [88]:
print(np.dot(a,b)) 

[[19 22]
 [43 50]]


In [89]:
print(a*b)

[[ 5 12]
 [21 32]]


In [27]:
def ke(a, b):
    dim = a.shape[0]
    m = b-a
    eig,_ = np.linalg.eig(m)
    n =len(eig)
    for i in range(n):
        if eig[i] >=0:
            eig[i]=0
        else:
            eig[i]=-eig[i]
    e= np.eye(dim,dtype= float)
    for i in range(dim):
        e[i][i]=eig[i]
    
    Ke = 1-np.linalg.norm(e)/np.linalg.norm(a)
    return Ke

In [28]:
def compute_Ke(listA,listB, method ='add'):
    '''
    imput two phrase or sentences lists
    tokenize each pair and get new dm using composition method
    compute Ke pred for each pair
    if oov set Ke to oov  # after test all in voc

    composition method
    add or pointwise
    '''
    method = 'add'  # 'poitwise'


    n = len(listA)
    if method == 'add':
        Ke_list = []
        for i in range(n):
            phraseA = listA[i].split()
            phraseB = listB[i].split()
            newA = dic[phraseA[0].lower()]+ dic[phraseA[1].lower()]
            newB = dic[phraseB[0].lower()]+ dic[phraseB[1].lower()]
            Ke_list.append(ke(newA, newB))

    if method == 'pointwise':
        Ke_list = []
        for i in range(n):
            phraseA = listA[i].split()
            phraseB = listB[i].split()
            newA = dic[phraseA[0].lower()] * dic[phraseA[1].lower()]
            newB = dic[phraseB[0].lower()] * dic[phraseB[1].lower()]
            Ke_list.append(ke(newA, newB))
    return Ke_list

In [133]:
result = compute_Ke(dicA,dicB)

In [134]:
result

[0.419627157210528,
 0.3889872690910656,
 0.4589475486338942,
 0.5479744692862214,
 0.2526255361556635,
 0.35308386187948004,
 0.3818822852395747,
 0.38827462898808296,
 0.33805260589695574,
 0.31269399320420366,
 0.28285004851295437,
 0.34071406107111324,
 0.35181190085400416,
 0.3290723244677125,
 0.45178260917390733,
 0.4851240021802018,
 0.4841757128781693,
 0.41804349361829785,
 0.44020328315763746,
 0.39074274207461845,
 0.35677144507789127,
 0.594689987237933,
 0.4053325002254996,
 0.2376209738242503,
 0.23208639950971388,
 0.26073428950744704,
 0.6249476755745128,
 0.6140719758474287,
 0.3676793570203025,
 0.2811029401061692,
 0.32234761116711863,
 0.3698949677280706,
 0.3633315475395582,
 0.4350032325311649,
 0.39298054403787286,
 0.4076644779431251,
 0.36641521775770014,
 0.49388080141865787,
 0.6180966800322165,
 0.5978537180312522,
 0.5908606604687281,
 0.632929271490416,
 0.233917062547371,
 0.28770353006185767,
 0.28953188907827354,
 0.3745059245547173,
 0.360170598527605

In [110]:
a =dic['explore']

In [111]:
b = dic['investigate']

In [112]:
ke(a,b)

-0.2808689258436199

In [114]:
a

array([[ 0.03378086,  0.00549287, -0.00482418,  0.0282998 , -0.03277893,
         0.00677299, -0.00898424,  0.02719941, -0.01663419, -0.00640014,
         0.01068765,  0.00615432, -0.00341644, -0.00599948,  0.00622409,
         0.02139806, -0.01823217],
       [ 0.00549287,  0.06552526,  0.02299628, -0.01947559, -0.07362977,
        -0.03167291, -0.00488665,  0.01048529, -0.02536271, -0.03631519,
        -0.00164473,  0.0137358 , -0.05905371, -0.00797473, -0.03494678,
         0.04384561, -0.03996505],
       [-0.00482418,  0.02299628,  0.04441347, -0.0145603 , -0.0244155 ,
        -0.01562658, -0.00335775,  0.01939947,  0.007849  , -0.01471949,
        -0.00895208,  0.01920741, -0.02304851, -0.00480977, -0.02305984,
         0.02981469, -0.03824382],
       [ 0.0282998 , -0.01947559, -0.0145603 ,  0.05489   , -0.00522654,
         0.00890493, -0.01092476,  0.03176883, -0.01239996,  0.00113469,
         0.00496694,  0.004902  ,  0.02688258, -0.01602529,  0.01889445,
         0.0077433 

In [115]:
m= b-a

In [116]:
eig,_ = np.linalg.eig(m)

In [117]:
eig

array([ 0.52611418, -0.34656243, -0.12231279,  0.05852545,  0.04470746,
       -0.05937203, -0.05642507, -0.0472867 ,  0.02766264,  0.02080932,
       -0.02748301, -0.01683073,  0.00838494, -0.00880883,  0.0037338 ,
       -0.00324647, -0.00160975])

In [121]:
for i in range(17):
    if eig[i] >=0:
        eig[i]=0
    else:
        eig[i]=-eig[i]

In [122]:
eig

array([0.        , 0.34656243, 0.12231279, 0.        , 0.        ,
       0.05937203, 0.05642507, 0.0472867 , 0.        , 0.        ,
       0.02748301, 0.01683073, 0.        , 0.00880883, 0.        ,
       0.00324647, 0.00160975])

In [125]:
for i in eig:
    if i ==0:
        i =2

In [126]:
eig

array([0.        , 0.34656243, 0.12231279, 0.        , 0.        ,
       0.05937203, 0.05642507, 0.0472867 , 0.        , 0.        ,
       0.02748301, 0.01683073, 0.        , 0.00880883, 0.        ,
       0.00324647, 0.00160975])

In [129]:
a = [1,2,3,4]
for i in a:
    i = i+1

In [130]:
a

[1, 2, 3, 4]

In [136]:
n = len(val)
for i in range(n):
    if val[i]=='T\n':
        val[i]=1
    else:
        val[i]=0

In [138]:
type(val)

list

In [139]:
from sklearn.metrics import roc_auc_score

In [141]:
roc_auc_score(val,result)

0.44351165980795615

In [31]:
import numpy as np
source1 = "F:/MSc DS/Project/dms/trained_dms_txt/bert2dm-pca.txt"
source2 = "F:/MSc DS/Project/dms/trained_dms_txt/bert2dm-pca-cls.txt"
source3 = "F:/MSc DS/Project/dms/trained_dms_txt/bert2dm-svd.txt"
source4 = "F:/MSc DS/Project/dms/trained_dms_txt/bert2dm-svd-cls.txt"
source5 = "F:/MSc DS/Project/dms/trained_dms_txt/ms-word2dm-c5.txt"
source6 = "F:/MSc DS/Project/dms/trained_dms_txt/ms-word2dm-c10.txt"
source7 = "F:/MSc DS/Project/dms/trained_dms_txt/ms-word2dm-d5.txt"
source8 = "F:/MSc DS/Project/dms/trained_dms_txt/ms-word2dm-d10.txt"
source9 = "F:/MSc DS/Project/dms/trained_dms_txt/word2dm.txt"

# dim = 17 #

def get_dict_from_source(source = source5,dim =17):
    if source ==source1 or source==source3:
        dim = 15
    whole =[]

    with open(source) as f:
        for line in f:
            linelist = line.split()
            for a in linelist:
                whole.append(a)
    chunk = dim**2+1
    n = len(whole)/chunk
    voc = []
    for i in range(int(n)):
        voc.append(whole[i * chunk])
    dic = {}
    for i in range(int(n)):
        voc.append(whole[i * chunk])
    dic = {}
    for i in range(int(n)):
        a = whole[i * chunk + 1:(i + 1) * chunk]
        a = np.array(a, dtype='float')
        a.resize([dim, dim])
        dic[voc[i]] = a

    return dic


def ke(a, b):
    dim = a.shape[0]
    m = b - a
    eig, _ = np.linalg.eig(m)
    n = len(eig)
    for i in range(n):
        if eig[i] >= 0:
            eig[i] = 0
        else:
            eig[i] = -eig[i]
    e = np.eye(dim, dtype=float)
    for i in range(dim):
        e[i][i] = eig[i]

    Ke = 1 - np.linalg.norm(e) / np.linalg.norm(a)
    return Ke

def compute_Ke(listA,listB, dic, method ='add'):
    '''
    imput two phrase or sentences lists
    tokenize each pair and get new dm using composition method
    compute Ke pred for each pair
    if oov set Ke to oov  # after test all in voc

    composition method
    add or pointwise
    '''

    n = len(listA)
    if method == 'add':
        Ke_list = []
        for i in range(n):
            phraseA = listA[i].split()
            phraseB = listB[i].split()
            newA = dic[phraseA[0].lower()] + dic[phraseA[1].lower()]
            newB = dic[phraseB[0].lower()] + dic[phraseB[1].lower()]
            Ke_list.append(ke(newA, newB))

    if method == 'pointwise':
        Ke_list = []
        for i in range(n):
            phraseA = listA[i].split()
            phraseB = listB[i].split()
            newA = dic[phraseA[0].lower()] * dic[phraseA[1].lower()]
            newB = dic[phraseB[0].lower()] * dic[phraseB[1].lower()]
            Ke_list.append(ke(newA, newB))
    return Ke_list


# get sv dataset
with open("F:/MSc DS/Project/compositional datasets/KS2016-SV.txt") as f:
    for line in f:
        linelist = line.split(",")
        dicA.append(linelist[0])
        dicB.append(linelist[1])
        val.append(linelist[2])

# convert the T to 1 F to 0 in val list
n = len(val)
for i in range(n):
    if val[i]=='T\n':
        val[i]=1
    else:
        val[i]=0
# dicA  list to store the first phrase
# dicB  list to store the second pharse
# val  true val


# test different source with different composition methods



In [146]:

# source1
dic1 = get_dict_from_source(source1)
# add method
pred = compute_Ke(dicA, dicB,dic1)
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

# pointwise
# pred = compute_Ke(dicA, dicB,dic1,method='pointwise')
# from sklearn.metrics import roc_auc_score
# result = roc_auc_score(val, pred)
# print(result

0.4788806584362141


In [147]:
pred = compute_Ke(dicA, dicB,dic1,method='pointwise')
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

0.48395061728395067


In [148]:
dic1 = get_dict_from_source(source6)
# add method
pred = compute_Ke(dicA, dicB,dic1)
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

0.48009876543209884


In [149]:
pred = compute_Ke(dicA, dicB,dic1,method='pointwise')
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

0.4340411522633745


In [32]:
# source2
dic1 = get_dict_from_source(source2)
# add method
pred = compute_Ke(dicA, dicB,dic1)
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

# pointwise
# pred = compute_Ke(dicA, dicB,dic1,method='pointwise')
# from sklearn.metrics import roc_auc_score
# result = roc_auc_score(val, pred)
# print(result

0.506238683127572


In [33]:
pred = compute_Ke(dicA, dicB,dic1,method='pointwise')
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

0.5294156378600823


In [34]:
# source3
dic1 = get_dict_from_source(source3)
# add method
pred = compute_Ke(dicA, dicB,dic1)
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

# pointwise
# pred = compute_Ke(dicA, dicB,dic1,method='pointwise')
# from sklearn.metrics import roc_auc_score
# result = roc_auc_score(val, pred)
# print(result

0.4998189300411523


In [35]:
pred = compute_Ke(dicA, dicB,dic1,method='pointwise')
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

0.5556213991769547


In [36]:
# source4
dic1 = get_dict_from_source(source4)
# add method
pred = compute_Ke(dicA, dicB,dic1)
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

# pointwise
# pred = compute_Ke(dicA, dicB,dic1,method='pointwise')
# from sklearn.met

0.5098271604938271


In [37]:
pred = compute_Ke(dicA, dicB,dic1,method='pointwise')
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

0.5590781893004115


In [38]:
# source5
dic1 = get_dict_from_source(source5)
# add method
pred = compute_Ke(dicA, dicB,dic1)
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

# pointwise
# pred = compute_Ke(dicA, dicB,dic1,method='pointwise')
# from sklearn.met

0.48724279835390943


In [39]:
pred = compute_Ke(dicA, dicB,dic1,method='pointwise')
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

0.4848395061728395


In [40]:
# source5
dic1 = get_dict_from_source(source7)
# add method
pred = compute_Ke(dicA, dicB,dic1)
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

# pointwise
# pred = compute_Ke(dicA, dicB,dic1,method='pointwise')
# from sklearn.met

0.4762798353909466


In [41]:
pred = compute_Ke(dicA, dicB,dic1,method='pointwise')
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

0.4457613168724279


In [42]:
# source5
dic1 = get_dict_from_source(source8)
# add method
pred = compute_Ke(dicA, dicB,dic1)
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

0.46610699588477367


In [43]:
pred = compute_Ke(dicA, dicB,dic1,method='pointwise')
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

0.43637860082304525


In [44]:
# source5
dic1 = get_dict_from_source(source9)
# add method
pred = compute_Ke(dicA, dicB,dic1)
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

0.5077201646090534


In [45]:
pred = compute_Ke(dicA, dicB,dic1,method='pointwise')
from sklearn.metrics import roc_auc_score
result = roc_auc_score(val, pred)
print(result)

0.4948806584362139
